### ISSUE TITLE
Group button with expand (2 buttons only)

### ISSUE THREAD

**Issue by nico3333fr** [ProtonMail/design-system#124]
## Quick summary of bug

![image](https://user-images.githubusercontent.com/2578321/57539223-54dc2b00-734a-11e9-9cf2-2ee363e2a3d1.png)

Spotted by @mmso 

## Possible fixes

I think I've found, I was using `last/first-of-type` pseudo selector, I think the problem comes from this, if I use `last/first-child`, it seems to work better.

Test all cases to see if this fixes.

**Comment by mmso** [comment]
Would it also be possible to change the name of `.pagination-expand-button` and `.pagination-expand-caret`

To remove the mention of `pagination`? For the dropdown actions f.e. it's not a pagination
just `.expand-button` and `expand-caret` perhaps? or something better if you have


I feel like `pagination-expand` is a bit weird also, is it really needed, or can we change it into something else? Because it seems to be just used to decide the border-radius of the button groupings now?

**Comment by nico3333fr** [comment]
Move the button styles to the dropdown. (consistency for all drop downs)
