### ISSUE TITLE
Blur effect in modal content

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/design-system#217]
When opening a modal, a light **blur effect** is added as a layer in the modal content. Can we fix that please? It's very disturbing for the UX.

Example:
![Capture d’écran 2019-09-05 à 12 02 16](https://user-images.githubusercontent.com/1345786/64332677-4094fb80-cfd5-11e9-8e8e-eec106e98fdf.png)

_Add attention to the text display in the modal and the text in the background. This last one is more clear than the content._

**Comment by nico3333fr** [comment]
After a lot of tests with @mmso , the problem is difficult to solve (and we are not the only ones to face it : https://stackoverflow.com/questions/14677490/blurry-text-after-using-css-transform-scale-in-chrome ). 

Anyway, `text-rendering: geometricPrecision;` and `-webkit-font-smoothing: antialiased;` seem to make it a bit better, I activate them now.
